# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dated', models.DateField()),
                ('dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['dated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='completed_drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dated', models.DateField()),
                ('dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['dated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='started',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dated', models.DateField()),
                ('dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_dau', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('yesterday_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('before_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('week_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('month_nu', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['dated'],
                'abstract': False,
            },
        ),
    ]
