# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160728_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='nu_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed_drop',
            name='nu_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='nu_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
