# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20160728_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='before_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='before_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='month_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='month_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='week_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='week_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='yesterday_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='yesterday_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='before_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='before_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='month_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='month_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='week_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='week_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='yesterday_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completeddrop',
            name='yesterday_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='before_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='before_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='month_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='month_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='week_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='week_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='yesterday_dau_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='started',
            name='yesterday_nu_compare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completed',
            name='dated',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='completeddrop',
            name='dated',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='started',
            name='dated',
            field=models.DateField(unique=True),
        ),
    ]
